CREATE TABLE IF NOT EXISTS "public"."job_applications" (
                                                           "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
                                                           "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
                                                           "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
                                                           "resume_id" "uuid" NOT NULL,
                                                           "job_id" "uuid" NOT NULL,
                                                           "optimized_resume_url" character varying
);
ALTER TABLE "public"."job_applications" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."jobs" (
                                               "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
                                               "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
                                               "name" character varying,
                                               "company" character varying,
                                               "description" "text" NOT NULL
);
ALTER TABLE "public"."jobs" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."resumes" (
                                                  "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
                                                  "user_id" "uuid" DEFAULT "auth"."uid"(),
                                                  "upload_url" character varying,
                                                  "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
                                                  "job_id" "uuid",
                                                  "resume_json" "jsonb"
);
ALTER TABLE "public"."resumes" OWNER TO "postgres";
CREATE TABLE IF NOT EXISTS "public"."user_quotas" (
                                                      "id" bigint NOT NULL,
                                                      "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
                                                      "user_id" "uuid" DEFAULT "auth"."uid"(),
                                                      "overall_optimize_quota" bigint DEFAULT '1'::bigint,
                                                      "partial_optimize_quota" bigint DEFAULT '10'::bigint,
                                                      "overall_optimize_used" bigint,
                                                      "partial_optimize_used" bigint,
                                                      "credits_quota" bigint DEFAULT '1'::bigint,
                                                      "credits_used" bigint
);
ALTER TABLE "public"."user_quotas" OWNER TO "postgres";
ALTER TABLE "public"."user_quotas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_quotas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );
ALTER TABLE ONLY "public"."job_applications"
    ADD CONSTRAINT "job_applications_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."jobs"
    ADD CONSTRAINT "jobs_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."resumes"
    ADD CONSTRAINT "resumes_id_key" UNIQUE ("id");
ALTER TABLE ONLY "public"."resumes"
    ADD CONSTRAINT "resumes_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."user_quotas"
    ADD CONSTRAINT "user_quotas_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."job_applications"
    ADD CONSTRAINT "job_applications_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."jobs"("id");
ALTER TABLE ONLY "public"."job_applications"
    ADD CONSTRAINT "job_applications_resume_id_fkey" FOREIGN KEY ("resume_id") REFERENCES "public"."resumes"("id");
ALTER TABLE ONLY "public"."job_applications"
    ADD CONSTRAINT "job_applications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");
ALTER TABLE ONLY "public"."resumes"
    ADD CONSTRAINT "resumes_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."jobs"("id");
ALTER TABLE ONLY "public"."resumes"
    ADD CONSTRAINT "resumes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");
ALTER TABLE ONLY "public"."user_quotas"
    ADD CONSTRAINT "user_quotas_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");
CREATE POLICY "Enable insert for authenticated users only" ON "public"."jobs" FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "Enable insert for users based on user_id" ON "public"."job_applications" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));
CREATE POLICY "Enable insert for users based on user_id" ON "public"."resumes" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));
CREATE POLICY "Enable insert for users based on user_id" ON "public"."user_quotas" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));
CREATE POLICY "Enable update for users based on user_id" ON "public"."resumes" FOR UPDATE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));
CREATE POLICY "Enable update for users based on user_id" ON "public"."user_quotas" FOR UPDATE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));
CREATE POLICY "Individuals can view their own resumes" ON "public"."resumes" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));
CREATE POLICY "Public job application are viewable only by authenticated users" ON "public"."job_applications" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));
CREATE POLICY "Public jobs are viewable only by authenticated users" ON "public"."jobs" FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Public user quatos are viewable only by authenticated users" ON "public"."user_quotas" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));
ALTER TABLE "public"."job_applications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."jobs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."resumes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."user_quotas" ENABLE ROW LEVEL SECURITY;
